# Generated by Django 4.2.15 on 2024-09-05 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('detail', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('fard', 'Fard'), ('sunnah', 'Sunnah'), ('nafl', 'Nafl')], max_length=25)),
                ('for_male', models.BooleanField()),
                ('for_female', models.BooleanField()),
                ('min_age', models.PositiveIntegerField()),
                ('for_married', models.BooleanField()),
                ('for_unmarried', models.BooleanField()),
                ('points', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=150)),
                ('number', models.PositiveIntegerField()),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Duties.task')),
            ],
        ),
        migrations.CreateModel(
            name='OldTaskCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('done_date', models.DateField()),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Duties.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=1000)),
                ('book', models.CharField(max_length=150)),
                ('number', models.CharField(max_length=100)),
                ('is_accepted', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('frequency', models.PositiveIntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Duties.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
