# Generated by Django 4.2.15 on 2024-09-07 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='book',
            field=models.CharField(choices=[('Bukhari', 'Bukhari'), ('Muslim', 'Muslim'), ('Abu Dawud', 'Abu Dawud'), ('Tirmidhi', 'Tirmidhi'), ("Nasa'i", "Nasa'i"), ('Ibn Majah', 'Ibn Majah')], max_length=50),
        ),
        migrations.CreateModel(
            name='Quran_References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surah', models.CharField(max_length=50)),
                ('number', models.PositiveIntegerField()),
                ('taskID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Duties.task')),
            ],
        ),
    ]
