# Generated by Django 4.2.15 on 2024-09-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0002_alter_references_book_quran_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='quran_references',
            name='ayah',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='references',
            name='hadith',
            field=models.CharField(default='', max_length=500),
        ),
    ]
