# Generated by Django 5.1 on 2024-08-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0002_checklist_feedback_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='for_male',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='for_married',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='min_age',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
    ]
