# Generated by Django 5.1 on 2024-08-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0003_task_for_male_task_for_married_task_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='for_female',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='for_unmarried',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
