# Generated by Django 5.1 on 2024-08-19 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0005_checklist_freqency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='last_done',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='checklist',
            name='freqency',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
