# Generated by Django 5.1 on 2024-08-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0006_rename_last_done_checklist_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='date',
            field=models.DateField(),
        ),
    ]
