# Generated by Django 5.1 on 2024-08-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0007_alter_checklist_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='taskID',
            new_name='task',
        ),
    ]
