# Generated by Django 5.1 on 2024-08-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0008_rename_taskid_checklist_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='freqency',
            new_name='frequency',
        ),
    ]
