# Generated by Django 5.1 on 2024-08-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0009_rename_freqency_checklist_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
