# Generated by Django 5.1 on 2024-08-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0010_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
