# Generated by Django 5.1 on 2024-08-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0013_oldtaskchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='references',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
