# Generated by Django 5.1 on 2024-08-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0014_references_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='number',
            field=models.CharField(max_length=100),
        ),
    ]
