# Generated by Django 5.1 on 2024-08-29 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Duties', '0015_alter_feedback_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='references',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='feedback',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
