# Generated by Django 5.1 on 2024-08-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtable',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
