# Generated by Django 5.1 on 2024-08-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0002_pointtable_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointtable',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
