# Generated by Django 5.1 on 2024-08-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaderboards', '0004_fardpercent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointtable',
            old_name='points',
            new_name='nafl_points',
        ),
        migrations.AddField(
            model_name='pointtable',
            name='fard_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pointtable',
            name='sunnah_percent',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='FardPercent',
        ),
    ]
